PREFIX vcard:<http://www.w3.org/2006/vcard/ns#>

select ?country (count(distinct ?org) as ?value) {
?org a vcard:Organization;
vcard:adr [vcard:country-name ?country]
} group by ?country order by desc(?value)
